name: Main Workflow Call

on:
  workflow_dispatch:
    inputs:
      runner_name:
        type: string

jobs:
  call-main:
    uses: ./.github/workflows/main.yaml
    with:
      runner: ${{ inputs.runner_name }}
