name: HOOPS main

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Generate test artifact
        run: |
          openssl rand -out artifact.txt 1G

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: test-${{ github.run_id }}
          name: "Automated test release"
          files: artifact.txt
