name: HOOPS main

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string

jobs:
  hoops_frontend:
    runs-on: ${{ inputs.runner }}
    env:
      REGISTRY_IMAGE: ${{ github.repository }}/${{ github.ref_name }}
    steps:
      - name: Значение переменной runner
        run: echo ${{ inputs.runner }}
